In [3]:
import pandas as pd

**Pandas Nedir ?**
* **
**Veri bilimi ve yapay zeka uygulamalarında kullanılan güzel bir kütüphanedir. Panel Data açılımı. Numpy dan farklı olarak yapısal veri setleri ile daha esnek ve kolay şekilde çalışabiliriz. Ekonometrik ve finansal çalışmalar için doğmuştur. R Dataframe yapısını Python dünyasına taşımış ve Dataframeler üzerinde hızlı ve etkin çalışabilme imkanı sağlamıştır.**


**Pandas Serisi Oluşturmak**
* **
* _**pd.Series([1,2,3,4])**_


ilk sütun serideki elemanların indeks numarası ikinci sütundaki değerler ise elemanların kendisidir. Pandas serileri değerleri indeksleri ile beraber tutar bu numpy arraylerinden bir farkıdır.

* _**seri.dtype**_ => seri içindeki verinin tipini verir.
* _**seri.axes**_ => seri indeks bilgilerini verir.
* _**seri.size**_ => seri içindeki eleman sayısını verir.
* _**seri.ndim**_ => serinin boyut sayısını verir.
* _**seri.values**_ => serinin tıpkı bir numpy array gibi erişim sağlatır.
* _**seri.head(args)**_ => seriye sayı bazlı erişim sağlar örnek 3 yazarsak ilk 3 elemanı indeksleriyle beraber getirir.
* _**seri.tail(args)**_ => seriye sayı bazlı erişim sağlar örnek 3 yazarsak son 3 elemanı indeksleriyle beraber getirir.

In [4]:
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
seri = pd.Series([1,2,3,4])
type(seri)

pandas.core.series.Series

In [7]:
seri.axes

[RangeIndex(start=0, stop=4, step=1)]

In [8]:
seri.dtype

dtype('int64')

In [9]:
seri.size

4

In [10]:
seri.ndim

1

In [11]:
seri.values

array([1, 2, 3, 4], dtype=int64)

In [15]:
seri.head(3)

0    1
1    2
2    3
dtype: int64

In [14]:
seri.tail(3)

1    2
2    3
3    4
dtype: int64

**İndeks isimlendirmesi**
* **
* pd.Series([99,22,232,94,5])

Eğer indeks numaralarını farklı yazmak istersek 

* pd.Series([99,22,232,94,5], index = [1,3,5,7,9])

Artık 0 1 2 3 4 yerine 1 3 5 7 9 yazacak

Aynı zamanda bu isimlendirmeleri String değerler ile de yapabiliriz.

In [16]:
pd.Series([99,22,232,94,5])

0     99
1     22
2    232
3     94
4      5
dtype: int64

In [17]:
pd.Series([99,22,232,94,5],index=[1,3,5,7,9])

1     99
3     22
5    232
7     94
9      5
dtype: int64

In [19]:
seri = pd.Series([99,22,232,94,5],index=["ahmet","mehmet","ayşe","fatma","reyyan"])

In [20]:
seri

ahmet      99
mehmet     22
ayşe      232
fatma      94
reyyan      5
dtype: int64

In [26]:
seri["reyyan"]
#sözlük mantığında key-values ilişkisi vardır.
seri["ahmet":"ayşe"]
#slice işlemi

ahmet      99
mehmet     22
ayşe      232
dtype: int64

In [25]:
#Sözlük üzerinden pandas serisi oluşturmak
sozluk = pd.Series({"reg":10,"log":11,"cart":12})
sozluk

reg     10
log     11
cart    12
dtype: int64

In [27]:
#İki seriyi birleştirerek yeni bir seri oluşturma
pd.concat([seri,sozluk])

ahmet      99
mehmet     22
ayşe      232
fatma      94
reyyan      5
reg        10
log        11
cart       12
dtype: int64

**Serilerde eleman işlemleri**
* **
* Eleman erişimi => a[0] indeksle erişim, slice a[0:3]
* Sadece index erişimi => seri.index
* Keys erişim => seri.keys
* list(seri.items()) => key-value şeklinde verir.
* seri.item => ilk elementi döner.
* seri.values => sadece değerlere erişim sağlar.
* seri.value_counts(True) => seri içindeki değerlerden yüzdelik kaç olduğunu gösterir.

In [28]:
import numpy as np
a = np.random.randint(10,99,size=5)
a

array([19, 28, 88, 16, 70])

In [29]:
seri = pd.Series(a)
seri

0    19
1    28
2    88
3    16
4    70
dtype: int32

In [30]:
seri[0]

19

In [31]:
seri[0:3]

0    19
1    28
2    88
dtype: int32

In [42]:
seri = pd.Series([121,200,150,99,121], index=["a","b","c","d","e"])
seri

a    121
b    200
c    150
d     99
e    121
dtype: int64

In [33]:
seri.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [34]:
seri.keys

<bound method Series.keys of a    121
b    200
c    150
d     99
dtype: int64>

In [36]:
list(seri.items())

[('a', 121), ('b', 200), ('c', 150), ('d', 99)]

In [37]:
seri.item

<bound method IndexOpsMixin.item of a    121
b    200
c    150
d     99
dtype: int64>

In [38]:
seri.values

array([121, 200, 150,  99], dtype=int64)

In [43]:
seri.value_counts(True)

121    0.4
200    0.2
150    0.2
99     0.2
dtype: float64