In [3]:
import pandas as pd

**Pandas Nedir ?**
* **
**Veri bilimi ve yapay zeka uygulamalarında kullanılan güzel bir kütüphanedir. Panel Data açılımı. Numpy dan farklı olarak yapısal veri setleri ile daha esnek ve kolay şekilde çalışabiliriz. Ekonometrik ve finansal çalışmalar için doğmuştur. R Dataframe yapısını Python dünyasına taşımış ve Dataframeler üzerinde hızlı ve etkin çalışabilme imkanı sağlamıştır.**


**Pandas Serisi Oluşturmak**
* **
* _**pd.Series([1,2,3,4])**_


ilk sütun serideki elemanların indeks numarası ikinci sütundaki değerler ise elemanların kendisidir. Pandas serileri değerleri indeksleri ile beraber tutar bu numpy arraylerinden bir farkıdır.

* _**seri.dtype**_ => seri içindeki verinin tipini verir.
* _**seri.axes**_ => seri indeks bilgilerini verir.
* _**seri.size**_ => seri içindeki eleman sayısını verir.
* _**seri.ndim**_ => serinin boyut sayısını verir.
* _**seri.values**_ => serinin tıpkı bir numpy array gibi erişim sağlatır.
* _**seri.head(args)**_ => seriye sayı bazlı erişim sağlar örnek 3 yazarsak ilk 3 elemanı indeksleriyle beraber getirir.
* _**seri.tail(args)**_ => seriye sayı bazlı erişim sağlar örnek 3 yazarsak son 3 elemanı indeksleriyle beraber getirir.

In [4]:
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
seri = pd.Series([1,2,3,4])
type(seri)

pandas.core.series.Series

In [7]:
seri.axes

[RangeIndex(start=0, stop=4, step=1)]

In [8]:
seri.dtype

dtype('int64')

In [9]:
seri.size

4

In [10]:
seri.ndim

1

In [11]:
seri.values

array([1, 2, 3, 4], dtype=int64)

In [15]:
seri.head(3)

0    1
1    2
2    3
dtype: int64

In [14]:
seri.tail(3)

1    2
2    3
3    4
dtype: int64

**İndeks isimlendirmesi**
* **
* pd.Series([99,22,232,94,5])

Eğer indeks numaralarını farklı yazmak istersek 

* pd.Series([99,22,232,94,5], index = [1,3,5,7,9])

Artık 0 1 2 3 4 yerine 1 3 5 7 9 yazacak

Aynı zamanda bu isimlendirmeleri String değerler ile de yapabiliriz.

In [16]:
pd.Series([99,22,232,94,5])

0     99
1     22
2    232
3     94
4      5
dtype: int64

In [17]:
pd.Series([99,22,232,94,5],index=[1,3,5,7,9])

1     99
3     22
5    232
7     94
9      5
dtype: int64

In [19]:
seri = pd.Series([99,22,232,94,5],index=["ahmet","mehmet","ayşe","fatma","reyyan"])

In [20]:
seri

ahmet      99
mehmet     22
ayşe      232
fatma      94
reyyan      5
dtype: int64

In [26]:
seri["reyyan"]
#sözlük mantığında key-values ilişkisi vardır.
seri["ahmet":"ayşe"]
#slice işlemi

ahmet      99
mehmet     22
ayşe      232
dtype: int64

In [25]:
#Sözlük üzerinden pandas serisi oluşturmak
sozluk = pd.Series({"reg":10,"log":11,"cart":12})
sozluk

reg     10
log     11
cart    12
dtype: int64

In [27]:
#İki seriyi birleştirerek yeni bir seri oluşturma
pd.concat([seri,sozluk])

ahmet      99
mehmet     22
ayşe      232
fatma      94
reyyan      5
reg        10
log        11
cart       12
dtype: int64

**Serilerde eleman işlemleri**
* **
* Eleman erişimi => a[0] indeksle erişim, slice a[0:3]
* Sadece index erişimi => seri.index
* Keys erişim => seri.keys
* list(seri.items()) => key-value şeklinde verir.
* seri.item => ilk elementi döner.
* seri.values => sadece değerlere erişim sağlar.
* seri.value_counts(True) => seri içindeki değerlerden yüzdelik kaç olduğunu gösterir.

In [28]:
import numpy as np
a = np.random.randint(10,99,size=5)
a

array([19, 28, 88, 16, 70])

In [29]:
seri = pd.Series(a)
seri

0    19
1    28
2    88
3    16
4    70
dtype: int32

In [30]:
seri[0]

19

In [31]:
seri[0:3]

0    19
1    28
2    88
dtype: int32

In [42]:
seri = pd.Series([121,200,150,99,121], index=["a","b","c","d","e"])
seri

a    121
b    200
c    150
d     99
e    121
dtype: int64

In [33]:
seri.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [34]:
seri.keys

<bound method Series.keys of a    121
b    200
c    150
d     99
dtype: int64>

In [36]:
list(seri.items())

[('a', 121), ('b', 200), ('c', 150), ('d', 99)]

In [37]:
seri.item

<bound method IndexOpsMixin.item of a    121
b    200
c    150
d     99
dtype: int64>

In [38]:
seri.values

array([121, 200, 150,  99], dtype=int64)

In [43]:
seri.value_counts(True)

121    0.4
200    0.2
150    0.2
99     0.2
dtype: float64

In [44]:
#Eleman sorgulama
"a" in seri

True

In [45]:
#Fancy index kullanımı
seri[["a","e"]]

a    121
e    121
dtype: int64

In [46]:
#Değer değiştirme
seri["e"] = 130

In [47]:
seri[["a","e"]]

a    121
e    130
dtype: int64

**Pandas Dataframe**
* **

*  import numpy as np
*  m = np.arrange(1,10).reshape((3,3))
* _**pd.DataFrame(m, columns = ["arg1","arg2","arg3"])**_
*  _**df.columns**_ değişken isimlerini getirir.

In [48]:
import numpy as np
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
pd.DataFrame(m,columns=["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [50]:
#df isimlendirme
df = pd.DataFrame(m,columns=["var1","var2","var3"])
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [51]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [54]:
# değişken isim değiştirme işlemi
df.columns = ("deg1","deg2","deg3")

In [53]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [55]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [56]:
df.shape

(3, 3)

In [57]:
df.ndim

2

In [58]:
df.size

9

In [59]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
df.tail(2)

deg1  deg2  deg3
1     4     5     6
2     7     8     9

In [62]:
#Eleman işlemleri
s1 = np.random.randint(10, size=5)
s2 = np.random.randint(10, size=5)
s3 = np.random.randint(10, size=5)

sozluk = {"var1":s1, "var2":s2, "var3":s3}
df = pd.DataFrame(sozluk)

df

var1  var2  var3
0     3     7     9
1     1     2     6
2     2     9     9
3     4     2     4
4     2     0     3

In [75]:
df[0:3]

var1  var2  var3
0     3     7     9
1     1     2     6
2     2     9     9

In [76]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [77]:
df.index = ["a","b","c","d","e"]

In [78]:
df

var1  var2  var3
a     3     7     9
b     1     2     6
c     2     9     9
d     4     2     4
e     2     0     3

In [79]:
df["c":"e"]

var1  var2  var3
c     2     9     9
d     4     2     4
e     2     0     3

In [80]:
#silme
df.drop("a",axis=0)

var1  var2  var3
b     1     2     6
c     2     9     9
d     4     2     4
e     2     0     3

In [82]:
df
#veri seti üstünde değişim olmadı

var1  var2  var3
a     3     7     9
b     1     2     6
c     2     9     9
d     4     2     4
e     2     0     3

In [ ]:
#eğer değişimin kalıcı olmasını istersek bu ifadeyi ekleyerek sağlayabiliriz.
df.drop("a",axis=0,inplace=True)

In [84]:
df

var1  var2  var3
b     1     2     6
c     2     9     9
d     4     2     4
e     2     0     3

In [85]:
df

var1  var2  var3
b     1     2     6
c     2     9     9
d     4     2     4
e     2     0     3

In [100]:
#fancy
l = ["c","e"]
df.drop(l,axis= 0)

var1  var2  var3
b     1     2     6
d     4     2     4

In [101]:
#değişkenler için
"var1" in df

True

In [105]:
l = ["var1","var4","var2"]

for i in l :
    print(i in df, end="-")

True-False-True-

In [115]:
#yeni bir değişken ekleme
df["var4"] = df["var1"]/df["var2"]

In [114]:
df

var1  var2  var3      var4
b     1     2     6  0.500000
c     2     9     9  0.222222
d     4     2     4  2.000000
e     2     0     3       inf

In [116]:
#değişken silme
df.drop("var4",axis=1)

var1  var2  var3
b     1     2     6
c     2     9     9
d     4     2     4
e     2     0     3

**Gözlem ve Değişken Seçimi**
* **


In [117]:
import numpy as np
import pandas as pd

m = np.random.randint(1,30, size=(10,3))
df = pd.DataFrame(m, columns=["var1","var2","var3"])
df

var1  var2  var3
0     3    23     1
1    15     4    15
2    27    10    27
3    25    14    24
4     4    14    24
5    23    19    29
6     8    11    27
7     5    21    23
8    11     9    14
9    19    13    15

In [124]:
#loc : tanımlandığı şekli ile seçim yapmak için kullanılır.
df.loc[0:3]
# burada 0 dan 3 dahil gözlem seçimi yaptı.

var1  var2  var3
0     3    23     1
1    15     4    15
2    27    10    27
3    25    14    24

In [140]:
#iloc : alışık olduğumuz indexleme mantığı ile seçim yapar.
df.iloc[0:3]
# burada 0 dan 3 e kadar gözlem seçimi yaptı.
# isimlendirmeden bağımsız işlem görür.

var1  var2  var3
0     3    23     1
1    15     4    15
2    27    10    27

In [126]:
df.iloc[0,0]

3

In [127]:
df.iloc[:3,:2]

var1  var2
0     3    23
1    15     4
2    27    10

In [129]:
df.loc[0:2,"var3"] #değişken-gözlem ikilisi için yaygın bu kullanılır.T

0     1
1    15
2    27
Name: var3, dtype: int32

In [131]:
df.iloc[0:3,1:3]

var2  var3
0    23     1
1     4    15
2    10    27

In [136]:
df.iloc[0:3]["var3"] #iloc ile değişken-gözlem ikilisi için bu kullanılır.

0     1
1    15
2    27
Name: var3, dtype: int32

**Koşullu Eleman İşlemleri**
* **


In [141]:
import numpy as np
import pandas as pd

m = np.random.randint(1,30, size=(10,3))
df = pd.DataFrame(m, columns=["var1","var2","var3"])
df

var1  var2  var3
0     1    28    14
1    22     8    29
2    20     5    12
3    28     7    18
4    28     4    21
5    13    28    23
6    10    21    29
7    25     3     7
8    21    20    26
9    26    27    25

In [143]:
df["var1"] > 15

0    False
1     True
2     True
3     True
4     True
5    False
6    False
7     True
8     True
9     True
Name: var1, dtype: bool

In [157]:
df[df.var1 > 15] #tek değişkenli filtreleme

var1  var2  var3
1    22     8    29
2    20     5    12
3    28     7    18
4    28     4    21
7    25     3     7
8    21    20    26
9    26    27    25

In [149]:
df[(df.var1 > 15) & (df.var3 < 5)] #çoklu şart filtrelemesi

Empty DataFrame
Columns: [var1, var2, var3]
Index: []

In [155]:
df[(df.var1 > 15)][["var1","var2"]]

var1  var2
1    22     8
2    20     5
3    28     7
4    28     4
7    25     3
8    21    20
9    26    27

In [156]:
df.loc[(df.var1 > 15) , ["var1","var2"]]

var1  var2
1    22     8
2    20     5
3    28     7
4    28     4
7    25     3
8    21    20
9    26    27

**Birleştirme (Join) İşlemleri**
* **

In [162]:
import numpy as np
import pandas as pd

m = np.random.randint(1,30, size=(5,3))
df1 = pd.DataFrame(m, columns=["var1","var2","var3"])
df1

var1  var2  var3
0    28     8    29
1    27    12     9
2    13    20     8
3    10    20    21
4    13    23    18

In [163]:
df2 = df1 + 99
df2

var1  var2  var3
0   127   107   128
1   126   111   108
2   112   119   107
3   109   119   120
4   112   122   117

In [164]:
pd.concat([df1,df2])

var1  var2  var3
0    28     8    29
1    27    12     9
2    13    20     8
3    10    20    21
4    13    23    18
0   127   107   128
1   126   111   108
2   112   119   107
3   109   119   120
4   112   122   117

In [170]:
pd.concat([df1,df2],ignore_index=True) #bu ifadeyi ekleyince indeks problemi ortadan kalkar.

var1  var2  var3
0    28     8    29
1    27    12     9
2    13    20     8
3    10    20    21
4    13    23    18
5   127   107   128
6   126   111   108
7   112   119   107
8   109   119   120
9   112   122   117

In [172]:
df1.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [173]:
df2.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [174]:
df2.columns = ["var1","var2","deg3"]

In [175]:
df2

var1  var2  deg3
0   127   107   128
1   126   111   108
2   112   119   107
3   109   119   120
4   112   122   117

In [176]:
df1

var1  var2  var3
0    28     8    29
1    27    12     9
2    13    20     8
3    10    20    21
4    13    23    18

In [180]:
pd.concat([df1,df2],ignore_index=True, join="inner")
#Kesisimlere göre birleştirildi.

var1  var2
0    28     8
1    27    12
2    13    20
3    10    20
4    13    23
5   127   107
6   126   111
7   112   119
8   109   119
9   112   122

**İleri Birleştirme İşlemleri**
* **

In [ ]:
import pandas as pd

In [186]:
#birebir birleştirme

df1 = pd.DataFrame({"calisanlar" : ["Ayse","Ali","Veli","Fatma"],
                    "grup":["Muhasabe","Muhendislik","Muhendislik","İK"]})
df1

calisanlar         grup
0       Ayse     Muhasabe
1        Ali  Muhendislik
2       Veli  Muhendislik
3      Fatma           İK

In [187]:
df2 = pd.DataFrame({"calisanlar" : ["Ayse","Ali","Veli","Fatma"],
                    "ilk_giris":[2010,2009,2014,2019]})
df2

calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [197]:
pd.merge(df1,df2, on="") #birleştirmelerin hangi değişkene göre yapılacağını belirtir. pk-fk ilişkisi


calisanlar         grup  ilk_giris
0       Ayse     Muhasabe       2010
1        Ali  Muhendislik       2009
2       Veli  Muhendislik       2014
3      Fatma           İK       2019

In [198]:
#many to one
df3 = pd.merge(df1,df2)
df3

calisanlar         grup  ilk_giris
0       Ayse     Muhasabe       2010
1        Ali  Muhendislik       2009
2       Veli  Muhendislik       2014
3      Fatma           İK       2019

In [199]:
df4 = pd.DataFrame({"grup":["Muhasabe","Muhendislik","İK"],
                    "mudur":["Caner","Mustafa","Berkcan"]})
df4

grup    mudur
0     Muhasabe    Caner
1  Muhendislik  Mustafa
2           İK  Berkcan

In [200]:
pd.merge(df3,df4)

calisanlar         grup  ilk_giris    mudur
0       Ayse     Muhasabe       2010    Caner
1        Ali  Muhendislik       2009  Mustafa
2       Veli  Muhendislik       2014  Mustafa
3      Fatma           İK       2019  Berkcan

In [202]:
#many to many
df5 = pd.DataFrame({"grup":["Muhasebe","Muhasebe",
                            "Muhendislik","Muhendislik","İK","İK"],
                            "yetenekler":["matematik","excel","kodlama","linux","excel","yonetim"]})

In [203]:
df5

grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           İK      excel
5           İK    yonetim

In [211]:
pd.merge(df1,df5)

calisanlar         grup yetenekler
0        Ali  Muhendislik    kodlama
1        Ali  Muhendislik      linux
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4      Fatma           İK      excel
5      Fatma           İK    yonetim