In [6]:
import numpy as np

**_Numerical Python açılımı.
Bilimsel hesaplamalar için kullanılır.
Arraylar / Çok boyutlu array ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.
Listelere benzer fakat verimli veri saklama ve vektörel operasyon sağlar._**

**Hücre çalıştırma => Shift + Enter**

**Notebook kuralları:**

* Silme => D + D

* Kesme => Dış tıkla + X

* Kopyalama => Dış tıkla + C

* Yapıştırma => Dış tıkla + V

**!! Hücre içinde code kısmında en son neyi yazdıysan onu çalıştırır.**

a = [1,2,3,4]
b = [2,3,4,5]

a

b

burada b çalışacak a çalışmayacaktır. Ama ikisini farklı hücrede çağırır isek ikiside çalışacaktır.



In [7]:
a = [1,2,3,4]
b = [2,3,4,5]





In [8]:
ab = []
for i in range(0,len(a)):
    ab.append(a[i]*b[i])
ab

[2, 6, 12, 20]

In [8]:


a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

a*b

array([ 2,  6, 12, 20])

In [13]:
c = np.array([12,3,4])
type(c)

numpy.ndarray

In [14]:
np.array([3.14,2,3])


array([3.14, 2.  , 3.  ])

**numpy arrayleri sabit tip baskısı sağlar**

* **eğer özel tip yapmak istersek numpy.array() içine dtype="" diyerek dtype içine istediğimiz number tipini koyabiliriz.**


In [16]:
np.array([1.1,2.2,3.4,4.5],dtype = "int")

array([1, 2, 3, 4])

**Sıfırdan array oluşturma işlemleri**

* _**np.zeros(10)** => 10 tane 0 dan oluşmuş bir array oluşturur._

* _**np.ones((3,5))** => 3 satır 5 sütunluk 1 lerden oluşmuş bir array_

* _**np.full((3,5),3)** => sadece 3 lerden oluşan 3 x 5 matris_

* _**np.arange(0,31,3)** => 0 dan 30 a kadar 3 er sıra ara ile lineer dizi oluşturur._

* _**np.linspace(0,1,10)** => 0 ile 1 arasında 10 adımlı lineer dizi oluşturur._

* _**np.random.normal(10,4, (3,4))** => ortalaması 10 standart sapması 4 olucak şekilde rastgele sayılardan üretilmiş bir 3 x 4 matris oluşturur._ => dağılım

* _**np.random.rand()** ve np.randint() rand() 0 ile 1 arasında randint verilen değer aralığında olucak rastgele sayılar ile matris oluşturur._





In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [21]:
np.ones((3,4),dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [23]:
np.full((4,4),31)

array([[31, 31, 31, 31],
       [31, 31, 31, 31],
       [31, 31, 31, 31],
       [31, 31, 31, 31]])

In [24]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [31]:
np.random.normal(2,14,(3,4))

array([[  3.45260665, -16.82690117,  17.33117437,  -2.61354252],
       [  1.79748655,   2.90953859,  11.57458003, -12.64151267],
       [  1.31726249,   8.05083932,  10.82648535,  -6.72807473]])

In [40]:
np.random.rand(2,3)

array([[0.45740461, 0.66621012, 0.22844002],
       [0.79606966, 0.1476813 , 0.10683871]])

In [38]:
np.random.randint(0,10,(3,3))

array([[4, 0, 5],
       [1, 2, 6],
       [8, 9, 0]])

**_np.random.randint(10, size=10)_** 0 dan 10 kadar farklı sayı veren size = 10 olan bir lineer dizi verir.

In [59]:
a = np.random.randint(10, size=10)

_**a.ndim**_ => boyut sayısını verir

_**a.shape**_ => boyut bilgisini verir eğer lineer bir dizi ise boyut bilgisi eleman sayısını eşittir.

_**a.size**_ => eleman sayısı verir

_**a.dtype**_ => array veri tipini verir

In [45]:
a.ndim


1

In [50]:
a.shape

(10,)

In [61]:
a.size

10

In [9]:
a.dtype

dtype('int32')

In [10]:
b = np.random.randint(10, size= (3,5))

In [11]:
b

array([[5, 8, 2, 2, 2],
       [5, 4, 9, 8, 0],
       [0, 9, 3, 6, 6]])

In [12]:
b.ndim

2

In [13]:
b.shape

(3, 5)

In [14]:
b.size

15

In [15]:
b.dtype

dtype('int32')

* _**np.reshape()**_ bize matrisi veya lineer bir dizinin boyutunu değiştirme imkanı sağlar.

In [10]:

arr = np.arange(1,10)

new_arr = arr.reshape((3,3))

new_arr





array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
array = np.arange(0,10).reshape((5,2))
array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

 **iki farklı numpy array birleştirme**
 * _**np.concatenate()**_ sayesinde tek boyutlu iki veya ikiden fazla np.array birleştirebiliriz. Aynı şekilde iki boyutlu matrisler içinde geçerli 

 * _**axis=**_ ise mevcut dizinin satır mı yoksa sütun bazında gözükmesini sağlar axis=0 satır axis=1 sütun şeklinde gösterir



In [12]:
a = np.array([1,2,3])
b = np.array([4,5,6])

concat = np.concatenate([a,b])

concat



array([1, 2, 3, 4, 5, 6])

In [20]:
a = np.random.randint(0,10,(3,3))

concat = np.concatenate([a,a], axis=1)

concat

array([[2, 2, 7, 2, 2, 7],
       [9, 7, 8, 9, 7, 8],
       [3, 4, 0, 3, 4, 0]])