In [52]:
import numpy as np

**_Numerical Python açılımı.
Bilimsel hesaplamalar için kullanılır.
Arraylar / Çok boyutlu array ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.
Listelere benzer fakat verimli veri saklama ve vektörel operasyon sağlar._**

**Hücre çalıştırma => Shift + Enter**

**Notebook kuralları:**

* Silme => D + D

* Kesme => Dış tıkla + X

* Kopyalama => Dış tıkla + C

* Yapıştırma => Dış tıkla + V

**!! Hücre içinde code kısmında en son neyi yazdıysan onu çalıştırır.**

a = [1,2,3,4]
b = [2,3,4,5]

a

b

burada b çalışacak a çalışmayacaktır. Ama ikisini farklı hücrede çağırır isek ikiside çalışacaktır.



In [53]:
a = [1,2,3,4]
b = [2,3,4,5]





In [54]:
ab = []
for i in range(0,len(a)):
    ab.append(a[i]*b[i])
ab

[2, 6, 12, 20]

In [55]:


a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

a*b

array([ 2,  6, 12, 20])

In [56]:
c = np.array([12,3,4])
type(c)

numpy.ndarray

In [57]:
np.array([3.14,2,3])


array([3.14, 2.  , 3.  ])

**numpy arrayleri sabit tip baskısı sağlar**

* **eğer özel tip yapmak istersek numpy.array() içine dtype="" diyerek dtype içine istediğimiz number tipini koyabiliriz.**


In [58]:
np.array([1.1,2.2,3.4,4.5],dtype = "int")

array([1, 2, 3, 4])

**Sıfırdan array oluşturma işlemleri**

* _**np.zeros(10)** => 10 tane 0 dan oluşmuş bir array oluşturur._

* _**np.ones((3,5))** => 3 satır 5 sütunluk 1 lerden oluşmuş bir array_

* _**np.full((3,5),3)** => sadece 3 lerden oluşan 3 x 5 matris_

* _**np.arange(0,31,3)** => 0 dan 30 a kadar 3 er sıra ara ile lineer dizi oluşturur._

* _**np.linspace(0,1,10)** => 0 ile 1 arasında 10 adımlı lineer dizi oluşturur._

* _**np.random.normal(10,4, (3,4))** => ortalaması 10 standart sapması 4 olucak şekilde rastgele sayılardan üretilmiş bir 3 x 4 matris oluşturur._ => dağılım

* _**np.random.rand()** ve np.randint() rand() 0 ile 1 arasında randint verilen değer aralığında olucak rastgele sayılar ile matris oluşturur._





In [59]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [60]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [61]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [62]:
np.ones((3,4),dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [63]:
np.full((4,4),31)

array([[31, 31, 31, 31],
       [31, 31, 31, 31],
       [31, 31, 31, 31],
       [31, 31, 31, 31]])

In [64]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [66]:
np.random.normal(2,14,(3,4))

array([[-14.80541673, -12.70684768,  -2.6423742 ,  12.25229482],
       [ -0.88685869, -26.16541208,   1.69961881,   4.99113281],
       [  8.81677738,   0.65666692,  -3.00306667,  11.90426592]])

In [67]:
np.random.rand(2,3)

array([[0.48312847, 0.93786755, 0.04268921],
       [0.69908073, 0.15259295, 0.70219752]])

In [68]:
np.random.randint(0,10,(3,3))

array([[4, 9, 3],
       [7, 8, 3],
       [1, 4, 1]])

**_np.random.randint(10, size=10)_** 0 dan 10 kadar farklı sayı veren size = 10 olan bir lineer dizi verir.

In [69]:
a = np.random.randint(10, size=10)

_**a.ndim**_ => boyut sayısını verir

_**a.shape**_ => boyut bilgisini verir eğer lineer bir dizi ise boyut bilgisi eleman sayısını eşittir.

_**a.size**_ => eleman sayısı verir

_**a.dtype**_ => array veri tipini verir

In [70]:
a.ndim


1

In [71]:
a.shape

(10,)

In [72]:
a.size

10

In [73]:
a.dtype

dtype('int32')

In [74]:
b = np.random.randint(10, size= (3,5))

In [75]:
b

array([[0, 1, 3, 0, 0],
       [6, 0, 4, 2, 7],
       [5, 4, 9, 9, 1]])

In [76]:
b.ndim

2

In [77]:
b.shape

(3, 5)

In [78]:
b.size

15

In [79]:
b.dtype

dtype('int32')

* _**np.reshape()**_ bize matrisi veya lineer bir dizinin boyutunu değiştirme imkanı sağlar.

In [80]:

arr = np.arange(1,10)

new_arr = arr.reshape((3,3))

new_arr





array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
array = np.arange(0,10).reshape((5,2))
array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

 **iki farklı numpy array birleştirme**
 * _**np.concatenate()**_ sayesinde tek boyutlu iki veya ikiden fazla np.array birleştirebiliriz. Aynı şekilde iki boyutlu matrisler içinde geçerli 

 * _**axis=**_ ise mevcut dizinin satır mı yoksa sütun bazında gözükmesini sağlar axis=0 satır axis=1 sütun şeklinde gösterir



In [82]:
a = np.array([1,2,3])
b = np.array([4,5,6])

concat = np.concatenate([a,b])

concat



array([1, 2, 3, 4, 5, 6])

In [83]:
a = np.random.randint(0,10,(3,3))

concat = np.concatenate([a,a], axis=1)

concat

array([[7, 1, 4, 7, 1, 4],
       [7, 4, 9, 7, 4, 9],
       [5, 1, 2, 5, 1, 2]])

**numpy arrayleri bölme işlemleri**

* _**np.split()**_ lineer dizileri bölmeyi sağlar.

* _**np.vsplit()**_ M x N boyutlu matrisi yatay olarak böler.

* _**np.hsplit()**_ M x N boyutlu matrisi dikey olarak
böler.

In [84]:
a = np.arange(16)

b,c,d = np.split(a,[3,11])

In [85]:
b

array([0, 1, 2])

In [86]:
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
d

array([11, 12, 13, 14, 15])

In [88]:
arr = np.arange(16).reshape((4,4))

arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [89]:
np.vsplit(arr,[3])

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

**numpy array sıralama**

* _**np.sort()**_ bu işlemi sağlar. Eğer matris üzerinde yapacak olursak da satır ve sütun olarak axis= kullanarak bu işlemi sağlarız.

In [90]:
m = np.random.randint(1,10,(3,4))

m

array([[6, 2, 7, 9],
       [6, 2, 3, 1],
       [8, 6, 7, 5]])

In [91]:
np.sort(m,axis=0)

array([[6, 2, 3, 1],
       [6, 2, 7, 5],
       [8, 6, 7, 9]])

In [92]:
np.sort(m, axis=1)

array([[2, 6, 7, 9],
       [1, 2, 3, 6],
       [5, 6, 7, 8]])

In [93]:
c = np.random.rand(10)

np.sort(c)

array([0.06925788, 0.15543769, 0.25406812, 0.51516183, 0.52007013,
       0.63604226, 0.68323634, 0.80847917, 0.93088385, 0.99599864])

**numpy arraylerde eleman işlemleri**

a = np.array([1,2,3]) 

 * a[0] = 1 bu şekilde erişim sağlanacaktır.

Ayrıca atama işlemi yaparak ilgili indexteki elemanın değerini değiştirebilirsin.

In [94]:
a = np.array([1,2,3,4,5])

a[0]

1

In [95]:
b = np.random.randint(10, size=(3,4))

b

array([[4, 6, 8, 9],
       [2, 1, 9, 1],
       [8, 6, 5, 4]])

In [96]:
b[1,3] = 12

b

array([[ 4,  6,  8,  9],
       [ 2,  1,  9, 12],
       [ 8,  6,  5,  4]])

**Tek boyutta alt indekse erişme işlemleri**

* _**a = np.arange(20,30)**_
* _**a[2::2]**_
* _array([22,24,26,28])_



In [100]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [101]:
a[2::2]

array([22, 24, 26, 28])

In [102]:
a[0::3]

array([20, 23, 26, 29])

**M x N matriste alt indekse erişim**

* **a = np.random.randint(1,10,(5,2))**
* **a**
* a[:,4] => tüm satırlar ilgili sütun
* a[1,:] => tüm sütunlar ilgili satır
* a[0:2,0:3] => 0 dan 2 ye tüm satır 0 dan 3 e tüm sütun
* a[::,:2] => tüm satırları al ilk 2 sütunu al

* **! seçilen alt küme üzerinde işlem yapıldığında sonuçları ana kümeyede yansır.**

In [109]:
a = np.random.randint(1,10,(5,5))

a

array([[7, 8, 5, 7, 1],
       [7, 6, 3, 8, 9],
       [8, 1, 1, 7, 5],
       [3, 6, 1, 9, 8],
       [8, 6, 2, 6, 9]])

In [120]:
a[:,4]

array([1, 9, 5, 8, 9])

In [126]:
a[1,:]

array([7, 6, 3, 8, 9])

In [124]:
a[0:2,0:3]

array([[7, 8, 5],
       [7, 6, 3]])

In [127]:
a[::,:2]

array([[7, 8],
       [7, 6],
       [8, 1],
       [3, 6],
       [8, 6]])

**Alt kümeleri bağımsızlaştırmak**

* _**np.copy()**_ bunu bize sağlıyor arrayin alt kümesinin bir kopyasını değişkene atayıp üzerinde spesifik işlemler yapmamıza olanak sağlamak ile beraber ana array üzerinde hiçbir değişiklik yaşatmıyor.

In [130]:
a = np.random.randint(10, size=(5,5))
a

array([[1, 6, 0, 7, 2],
       [7, 2, 6, 1, 2],
       [3, 1, 0, 9, 0],
       [8, 6, 7, 6, 0],
       [7, 8, 5, 0, 8]])

In [131]:
alt_a = a[0:3,0:2]
alt_a

array([[1, 6],
       [7, 2],
       [3, 1]])

In [132]:
alt_a[0,0] = 9999999

In [133]:
alt_a

array([[9999999,       6],
       [      7,       2],
       [      3,       1]])

In [134]:
alt_a[1,1] = 33

In [135]:
alt_a

array([[9999999,       6],
       [      7,      33],
       [      3,       1]])

In [136]:
a

array([[9999999,       6,       0,       7,       2],
       [      7,      33,       6,       1,       2],
       [      3,       1,       0,       9,       0],
       [      8,       6,       7,       6,       0],
       [      7,       8,       5,       0,       8]])

In [137]:
m = np.random.randint(10,size=(5,5))
m 

array([[8, 1, 7, 9, 6],
       [6, 6, 7, 0, 9],
       [2, 0, 7, 2, 7],
       [6, 2, 5, 0, 2],
       [2, 5, 8, 9, 7]])

In [138]:
alt_m = np.copy(m[0:2,0:3])
alt_m

array([[8, 1, 7],
       [6, 6, 7]])

In [139]:
alt_m[0,0] = 99999
alt_m

array([[99999,     1,     7],
       [    6,     6,     7]])

In [140]:
m

array([[8, 1, 7, 9, 6],
       [6, 6, 7, 0, 9],
       [2, 0, 7, 2, 7],
       [6, 2, 5, 0, 2],
       [2, 5, 8, 9, 7]])

**Fancy index kavramı**
* bu kavram çoğunlukla bir döngü veya işlem sonrası oluşacak çok büyük miktardaki veriye erişimi bir liste içine atayarak erişme esasına dayanıyor.

In [141]:
vektor = np.arange(10)
vektor

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
fancy = [vektor[0:3]]

In [147]:
fancy

[array([0, 1, 2])]

In [151]:
matris = np.arange(16).reshape(4,4)
matris

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [161]:
satir = np.array([1,2])
sütun = np.array([2,3])
fancy = m[satir,sütun]
fancy

array([7, 2])

In [162]:
fancy = m[0:,[satir]]
fancy

array([[[1, 7]],

       [[6, 7]],

       [[0, 7]],

       [[2, 5]],

       [[5, 8]]])

**Koşullu eleman işlemleri**



In [163]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
arr < 4 

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [165]:
#fancy ile sonuçlara erişme 
arr[arr < 4]

array([0, 1, 2, 3])

In [166]:
arr[arr > 3]

array([4, 5, 6, 7, 8, 9])

In [167]:
arr[arr >= 3]

array([3, 4, 5, 6, 7, 8, 9])

In [168]:
arr[arr <= 3]

array([0, 1, 2, 3])

In [169]:
arr[arr == 3]

array([3])

In [170]:
arr[arr != 3]

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [171]:
arr * 2


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [172]:
arr / 5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [173]:
arr*5/10

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [174]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

**Numpy matematiksel işlemler**
